### ISSUE TITLE
Styling inconsistencies and minor bug

### ISSUE THREAD

**Issue by tiisetsohub** [tiisetsohub/GiveALittle#1]
Once you click on an item to view it on the home page or landing page, there's no button to close the product view forcing you to refresh the page

The images are cropped and don't show the item clearly

The button in the seller's landing page doesn't follow the already existing sharper shapes and golden colour styling schemes already in place

The text in the cart is also way too high up and not in line with the respective item image

The item blocks in the seller's landing page text size is inconsistent with that of those in the home and landing page

**Comment by tiisetsohub** [comment]
Also text in navbar out of line with search bar and button

**Comment by Brianhulela** [comment]
Product view close button fixed.
Image cropping fixed.
Inconsistent color and rounded button edges fixed.
Centered cart text with image.

Pending
1. Sellers Landing Page style issues.
2. Text in navbar out of line with search bar and button.
