### ISSUE TITLE
Hover on review

### ISSUE THREAD

**Issue by Pamela271097** [tiisetsohub/GiveALittle#16]
Reviews do not show, Button unclickable.

**Comment by Turtle-art** [comment]
I'm having the same issue, someone else changed the code in Home.js. I am looking into it now

**Comment by Turtle-art** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/71205359/171562615-dc1d2f97-99fe-44da-a61c-afecc407489d.png)
![Screenshot (14)](https://user-images.githubusercontent.com/71205359/171562620-6d52aba8-751c-4ab2-ba89-98ce7c88d629.png)

Fixed and pushed to main. Pamela you were fetching stars incorrectly
